---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/mo6020/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Repositories/Dotfiles
dotfiles_files:
  - .osx
  - .tmux.conf
  - .vimrc
  - .zshrc
  - bullet-train.zsh-theme
  - Tomorrow-Night-Eighties.vim
  - Tomorrow-Night-Eighties.itermcolors
  - nord.vim
  - Nord.itermcolors

homebrew_installed_packages:
  - ansible
  - azure-cli
  - bat
  - chrome-cli
  - coreutils
  - findutils
  - fio
  - git
  - git-credential-manager
  - gnupg
  - gnutls
  - go
  - google-cloud-sdk
  - jq
  - httpie
  - htop
  - mas
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - pip
  - git-flow
  - wget
  - tmux
  - reattach-to-user-namespace
  - ruby
  - nvm
  - python
  - npm
  - vim
  - terraform
  - vault
  - wget

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adobe-creative-cloud
  - android-file-transfer
  - aerial
  - balenaetcher
  - bartender
  - discord
  - disk-inventory-x
  - docker
  - dropbox
  - elgato-control-center
  - evernote
  - flux
  - focusrite-control
  - ghostty
  - google-chrome
  - gpg-suite
  - macdown
  - macvim
  - notion
  - onyx
  - qobuz
  - protonvpn
  - roon
  - simplenote
  - spectacle
  - superhuman
  - the-unarchiver
  - todoist
  - transmit
  - tuxera-ntfs
  - vlc
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.

mas_installed_apps:
  - {id: 1295203466, name: "Microsoft Remote Desktop"}
  - {id: 913724705, name: "Disk Care"}
  - {id: 1464122853, name: "NextDNS"}
  - {id: 1091189122, name: "Bear"}
  - {id: 1508343025, name: "Mimir"}
  - {id: 634148309, name: "Logic Pro"}
  - {id: 634148309, name: "UpNote"}

osx_script: "~/.osx --no-restart"

pip_packages:
  - name: powerline-status
  - name: powerline-gitstatus
  - name: rubrik_cdm
